sudo: required
language: ruby
rvm:
- 2.4.0
install:
- gem install bundler
- bundle install
script:
- bundle exec rake test
deploy:
  provider: rubygems
  gemspec: deadman_check.gemspec
  api_key:
    secure: rcQ8I4cBn+UpROxhBUsldKbpiiZ9QNUEep8fLGbmcU6QqN5NA2VrdW/DDzXrgXPPLoTDxRF32K2clIjT6WHYopVOvCeAA0+kNjACtGEV8DKL5VlBz0yWvLqM5L7y6ZhmiL/XUibmN7jcvqqI96h2QRr3qeO4a3XUlAIBqotjMopkqqBcHfq9+19p8CS3yS9Y85c1mM5EDcP7E/3Sa3umK7vvoMh+ulz1mic/CNKSnJOdhicqspvpPLUP0vOZ4Jlnn8I41clkBA0FcbOvEmEU2GNtMR8xDS9e0t+aVBAD92AiKYlHNzWp/84r3ZNjMURmltSLRHOQKYQhFdNJUNxZj9f44mPZcMIqD1kkKFkrdzjRzqpGxldrlUwgGkdiFev9d3x8XYMybDI3SmFDPNfa8d7DeW/AYIwkW6j7rdaFQQLzG4AZnoaW6FOmldePk0hPDT47wdpVy5nItH8ZQax8qJmDOX46IRr4fZ6piXiWZlSIfdwUtdBD47fmZS9xxi+mKTggZYiy+th3txqaXORJCCaaJVo5Yg1hbMN73+yKtLtzmsw/nKr1yVVX3KhYQkNix3ZskNhuOJ2aN2stnVsYKbL0Y924sVp7OrSyg5cWqXEXYcWGpXOKlaABa593QFGwQGl6wo7JiFO7giMQw0n6B4xkRv910BBXSVzafHk+jwk=
  on:
    tags: true
env:
  global:
    secure: rcQ8I4cBn+UpROxhBUsldKbpiiZ9QNUEep8fLGbmcU6QqN5NA2VrdW/DDzXrgXPPLoTDxRF32K2clIjT6WHYopVOvCeAA0+kNjACtGEV8DKL5VlBz0yWvLqM5L7y6ZhmiL/XUibmN7jcvqqI96h2QRr3qeO4a3XUlAIBqotjMopkqqBcHfq9+19p8CS3yS9Y85c1mM5EDcP7E/3Sa3umK7vvoMh+ulz1mic/CNKSnJOdhicqspvpPLUP0vOZ4Jlnn8I41clkBA0FcbOvEmEU2GNtMR8xDS9e0t+aVBAD92AiKYlHNzWp/84r3ZNjMURmltSLRHOQKYQhFdNJUNxZj9f44mPZcMIqD1kkKFkrdzjRzqpGxldrlUwgGkdiFev9d3x8XYMybDI3SmFDPNfa8d7DeW/AYIwkW6j7rdaFQQLzG4AZnoaW6FOmldePk0hPDT47wdpVy5nItH8ZQax8qJmDOX46IRr4fZ6piXiWZlSIfdwUtdBD47fmZS9xxi+mKTggZYiy+th3txqaXORJCCaaJVo5Yg1hbMN73+yKtLtzmsw/nKr1yVVX3KhYQkNix3ZskNhuOJ2aN2stnVsYKbL0Y924sVp7OrSyg5cWqXEXYcWGpXOKlaABa593QFGwQGl6wo7JiFO7giMQw0n6B4xkRv910BBXSVzafHk+jwk=
'':
  travis:
    yml:
      secure: sJE+8NjpQarrV2j9CXM9mu29iTVRX9rF1BPwdbnmZAYFlnTnUH9mlDbHGJCp4jN3nbcFgki428AAjREt11kGasj6aCqzjfE+4l6owlyckJdGtfUmivKe5KSXJbn6Rnt+w5jZzI9oybRy8Q6D6Yb7DSLUWU7+GDgzAdyScc+keM2k6TIBKaIM/lFzQbRAh2f8B1CryU8VdSbGNoAxuG6WSa9E5Zp9DQyT7fgwt5LUQXi7ulrR7IloJ58HSE7cg9Kt3h918gxQKrqUMhIjHxkhb6bOzXjdZNeOObG5MhKfVS4YxlggGLSFBJ45wDF+CH2CMFO/wz1Z3bASkRmOsSas8NZqE8I6FRJD0E65mtrqHtAh7qZuVmqEF8ks37ZGQLPRVIjQnW386Kgxbrdv0NEIBUWpywR3csTuVOlemg9dyI73X3YjuZYXl0UwStmIbUhFEo5MdcyC3SERp3OJtniwt1f2x7ZCbLCK/Ba5E4CBcxJ5tqxoSkcXsjm2UU7fq3doIv44VHqTkdpo54E+NvjBoPx5ZqrPWmDm9JebMXCxI3HO0LiHSDW0NH5VrhG1h/ps/fVQSOSzq8geP25UqG6GvhM/U7VB+NsYEZpe76rbc4mbwt72FB3xn0xrBEZX3aQGY+uyrp4qRLTPutm+wS4zEjkP0SF5bxoLFIBpbd049XQ=
